<?php

return [
    // Common
    'subscription_payments' => 'Subscription Payments',
    'manage_track_payments' => 'Manage and track subscription payment records',
    'payment_receipt' => 'Payment Receipt',
    'payment_details' => 'Payment details and transaction information',
    'subscription_details' => 'Subscription Details',
    'back' => 'Back',
    'print' => 'Print',
    'download' => 'Download',
    'export' => 'Export',
    'search' => 'Search',
    'filter' => 'Filter',
    'clear' => 'Clear',
    'actions' => 'Actions',
    'status' => 'Status',
    'view' => 'View',
    'delete' => 'Delete',
    'method' => 'Method',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'days' => 'Days',
    'date' => 'Date',
    'no_records_found' => 'No records found!',
    'amount_paid' => 'Amount Paid',
    'price' => 'Price',
    'timeline' => 'Timeline',
    'subscription_report' => 'Subscription Report',
    'official_document' => 'Official Document',
    'subscription' => 'Subscription',
    'report_date' => 'Report Date',
    'company_info' => 'Company Information',
    'plan_name' => 'Plan Name',
    'total_price' => 'Total Price',
    'validity_days' => 'Validity (Days)',
    'report_id' => 'Report ID',
    'subscription_summary' => 'Subscription Summary',
    'transaction_id' => 'Transaction ID',
    'total_paid' => 'Total Paid',
    'duration' => 'Duration',
    'billing_info' => 'Billing Information',
    'generated_by' => 'Generated By',
    'computer_generated_report' => 'This is a computer-generated report. No signature required.',
    'valid_until' => 'Valid Until',
    'customer_info' => 'Customer Information',
    'reference_id' => 'Reference ID',


    // Status
    'completed' => 'Completed',
    'pending' => 'Pending',
    'failed' => 'Failed',
    'refunded' => 'Refunded',
    'active' => 'Active',
    'expired' => 'Expired',
    'cancelled' => 'Cancelled',
    'inactive' => 'Inactive',
    
    // Payment Methods
    'cash' => 'Cash',
    'card' => 'Credit Card',
    'bank' => 'Bank Transfer',
    'mobile' => 'Mobile Banking',
    'online' => 'Online Payment',
    
    // Table Headers
    'sl' => 'SL',
    'transaction_details' => 'Transaction Details',
    'subscription_info' => 'Subscription Info',
    'user' => 'User',
    'payment_method' => 'Payment Method',
    'amount' => 'Amount',
    'payment_date' => 'Payment Date',
    'days_remaining' => 'days remaining',
    
    // Form Labels
    'search_payments' => 'Search Payments',
    'payment_status' => 'Payment Status',
    'all_status' => 'All Status',
    'all_methods' => 'All Methods',
    
    // Summary
    'payments_summary' => 'Payments Summary',
    'total_payments' => 'Total Payments',
    'completed_payments' => 'Completed Payments',
    'total_revenue' => 'Total Revenue',
    'pending_payments' => 'Pending Payments',
    'payment_methods_breakdown' => 'Payment Methods Breakdown',
    
    // Messages
    'no_payment_records' => 'No payment records found!',
    'adjust_search_filters' => 'Try adjusting your search or filters',
    'no_payment_records_available' => 'No payment records available',
    'delete_confirmation' => 'Are you sure you want to delete this payment record?',
    
    // Payment View
    'payment_information' => 'Payment Information',
    'payment_id' => 'Payment ID',
    'transaction_ref' => 'Transaction Ref',
    'related_subscription' => 'Related Subscription',
    'subscription_id' => 'Subscription ID',
    'plan' => 'Plan',
    'plan_price' => 'Plan Price',
    'customer_information' => 'Customer Information',
    'processed_at' => 'Processed At',
    'last_updated' => 'Last Updated',
    'plan_details' => 'Plan Details',
    'billing_cycle' => 'Billing Cycle',
    'validity' => 'Validity',
    'payment_notes' => 'Payment Notes',
    
    // Subscription Show
    'subscription_information' => 'Subscription Information',
    'billing_information' => 'Billing Information',
    'user_information' => 'User Information',
    'member_since' => 'Member since',
    'subscription_timeline' => 'Subscription Timeline',
    'created' => 'Created',
    'started' => 'Started',
    'expires' => 'Expires',
    'next_billing' => 'Next Billing',
    'auto_renew' => 'Auto-renew',
    'yes' => 'Yes',
    'no' => 'No',
    'payment_history' => 'Payment History',
    'subscription_notes' => 'Subscription Notes',
    'reference' => 'Reference',
    
    // Receipt
    'official_payment_confirmation' => 'Official Payment Confirmation',
    'generated_on' => 'Generated on',
    'thank_you_business' => 'Thank you for your business!',
    'computer_generated_receipt' => 'This is a computer-generated receipt. No signature required.',
    
    // Placeholders
    'search_placeholder' => 'Search by transaction ID, user name, plan name...',
    
    // Required field
    'required_field' => '*',
];